<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtlasGT.Connectors.Abstractions\AtlasGT.Connectors.Abstractions.csproj" />
    <ProjectReference Include="..\AtlasGT.Domain\AtlasGT.Domain.csproj" />
    <ProjectReference Include="..\AtlasGT.Historian\AtlasGT.Historian.csproj" />
  </ItemGroup>
</Project>
