<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtlasGT.Application\AtlasGT.Application.csproj" />
    <ProjectReference Include="..\AtlasGT.Discovery\AtlasGT.Discovery.csproj" />
    <ProjectReference Include="..\AtlasGT.Domain\AtlasGT.Domain.csproj" />
    <ProjectReference Include="..\AtlasGT.Infrastructure\AtlasGT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.7.0" />
  </ItemGroup>

</Project>
